### PR TITLE
fix(cron): proper return type for `isTelemetryEnabled()`

### LINKED ISSUE #3314: [Bug] Build fails from #3313
### What Went Wrong?

PR #3313 was merged even while it was incomplete and had an error with the types

### How Can We Reproduce This?

1. `gradlew build`

### What Should Have Happened?

No compilation errors

### Screenshots or Error Messages (Optional)

_No response_

### Any Ideas on How to Fix This? (Optional)

_No response_

### Your Setup

- Booklore version `develop` branch
- OS: Arch Linux

### Before Submitting

- [x] I've searched existing issues and confirmed this bug hasn't been reported yet

### PR DESCRIPTION
**Pull request by imnotjames**
## 📝 Description

The PR in #3313 was merged in an incomplete state and lacked the correct return type for the new `isTelemetryEnabled()` helper.  Without this type, the build fails.

Fixes #3314

## 🏷️ Type of Change

- [x] Bug fix
- [ ] New feature
- [ ] Enhancement to existing feature
- [ ] Refactor (no behavior change)
- [ ] Breaking change (existing functionality affected)
- [ ] Documentation update

## 🔧 Changes

- change type from `void` to `boolean` on `isTelemetryEnabled()`

## 🧪 Testing (MANDATORY)

> **PRs without this section filled out will be closed.** "Tests pass" or "Tested locally" is not sufficient. You must provide specifics.

**Manual testing steps you performed:**

1. Compiled with `gradlew build`
2. Saw failed compilation
3. Updated type
4. Compiled again with `gradlew build`

**Regression testing:**

- Compilation failed before and does not fail now.  No other compilation failures occur.

**Edge cases covered:**

- No known edge cases.

**Test output:**

<details>
<summary>Backend test output (<code>./gradlew test</code>)</summary>

```
> Task :compileJava
Management of bidirectional association persistent attributes is deprecated and will be removed. Set the value to 'false' to get rid of this warning
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
WARNING: A terminally deprecated method in sun.misc.Unsafe has been called
WARNING: sun.misc.Unsafe::objectFieldOffset has been called by net.bytebuddy.dynamic.loading.ClassInjector$UsingUnsafe$Dispatcher$CreationAction (file:/home/james/.local/share/gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy/1.17.8/af5735f63d00ca47a9375fae5c7471a36331c6ed/byte-buddy-1.17.8.jar)
WARNING: Please consider reporting this to the maintainers of class net.bytebuddy.dynamic.loading.ClassInjector$UsingUnsafe$Dispatcher$CreationAction
WARNING: sun.misc.Unsafe::objectFieldOffset will be removed in a future release
2026-03-12T22:57:41.704-04:00  INFO 16922 --- [booklore-api] [opFolderWatcher] o.b.s.b.BookdropMonitoringService        : Bookdrop monitor thread interrupted
2026-03-12T22:57:41.706-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.b.s.b.BookdropMonitoringService        : Stopped bookdrop folder monitor
2026-03-12T22:57:41.755-04:00  INFO 16922 --- [booklore-api] [opFileProcessor] o.b.s.b.BookdropEventHandlerService      : File processing thread interrupted, shutting down.
2026-03-12T22:57:41.756-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.b.s.monitoring.LibraryWatchService     : Shutting down LibraryWatchService...
2026-03-12T22:57:41.757-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.b.s.watcher.LibraryFileEventProcessor  : Shutting down LibraryFileEventProcessor...
2026-03-12T22:57:41.757-04:00  WARN 16922 --- [booklore-api] [     watch-poll] o.b.s.monitoring.LibraryWatchService     : WatchService closed, stopping poll loop.
2026-03-12T22:57:41.767-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2026-03-12T22:57:41.780-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : BookloreHikariPool - Shutdown initiated...
2026-03-12T22:57:41.781-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : BookloreHikariPool - Shutdown completed.
2026-03-12T22:57:41.785-04:00  INFO 16922 --- [booklore-api] [opFolderWatcher] o.b.s.b.BookdropMonitoringService        : Bookdrop monitor thread interrupted
2026-03-12T22:57:41.785-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.b.s.b.BookdropMonitoringService        : Stopped bookdrop folder monitor
2026-03-12T22:57:41.785-04:00  INFO 16922 --- [booklore-api] [opFileProcessor] o.b.s.b.BookdropEventHandlerService      : File processing thread interrupted, shutting down.
2026-03-12T22:57:41.786-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.b.s.monitoring.LibraryWatchService     : Shutting down LibraryWatchService...
2026-03-12T22:57:41.787-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.b.s.watcher.LibraryFileEventProcessor  : Shutting down LibraryFileEventProcessor...
2026-03-12T22:57:41.787-04:00  WARN 16922 --- [booklore-api] [     watch-poll] o.b.s.monitoring.LibraryWatchService     : WatchService closed, stopping poll loop.
2026-03-12T22:57:41.796-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2026-03-12T22:57:41.799-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : BookloreHikariPool - Shutdown initiated...
2026-03-12T22:57:41.799-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : BookloreHikariPool - Shutdown completed.
2026-03-12T22:57:41.806-04:00  INFO 16922 --- [booklore-api] [opFolderWatcher] o.b.s.b.BookdropMonitoringService        : Bookdrop monitor thread interrupted
2026-03-12T22:57:41.806-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.b.s.b.BookdropMonitoringService        : Stopped bookdrop folder monitor
2026-03-12T22:57:41.806-04:00  INFO 16922 --- [booklore-api] [opFileProcessor] o.b.s.b.BookdropEventHandlerService      : File processing thread interrupted, shutting down.
2026-03-12T22:57:41.808-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.b.s.monitoring.LibraryWatchService     : Shutting down LibraryWatchService...
2026-03-12T22:57:41.808-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.b.s.watcher.LibraryFileEventProcessor  : Shutting down LibraryFileEventProcessor...
2026-03-12T22:57:41.808-04:00  WARN 16922 --- [booklore-api] [     watch-poll] o.b.s.monitoring.LibraryWatchService     : WatchService closed, stopping poll loop.
2026-03-12T22:57:41.819-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2026-03-12T22:57:41.832-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : BookloreHikariPool - Shutdown initiated...
2026-03-12T22:57:41.833-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : BookloreHikariPool - Shutdown completed.
2026-03-12T22:57:41.840-04:00  INFO 16922 --- [booklore-api] [opFolderWatcher] o.b.s.b.BookdropMonitoringService        : Bookdrop monitor thread interrupted
2026-03-12T22:57:41.840-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.b.s.b.BookdropMonitoringService        : Stopped bookdrop folder monitor
2026-03-12T22:57:41.840-04:00  INFO 16922 --- [booklore-api] [opFileProcessor] o.b.s.b.BookdropEventHandlerService      : File processing thread interrupted, shutting down.
2026-03-12T22:57:41.842-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.b.s.monitoring.LibraryWatchService     : Shutting down LibraryWatchService...
2026-03-12T22:57:41.842-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.b.s.watcher.LibraryFileEventProcessor  : Shutting down LibraryFileEventProcessor...
2026-03-12T22:57:41.842-04:00  WARN 16922 --- [booklore-api] [     watch-poll] o.b.s.monitoring.LibraryWatchService     : WatchService closed, stopping poll loop.
2026-03-12T22:57:41.853-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2026-03-12T22:57:41.865-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : BookloreHikariPool - Shutdown initiated...
2026-03-12T22:57:41.866-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : BookloreHikariPool - Shutdown completed.
2026-03-12T22:57:41.872-04:00  INFO 16922 --- [booklore-api] [opFolderWatcher] o.b.s.b.BookdropMonitoringService        : Bookdrop monitor thread interrupted
2026-03-12T22:57:41.872-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.b.s.b.BookdropMonitoringService        : Stopped bookdrop folder monitor
2026-03-12T22:57:41.873-04:00  INFO 16922 --- [booklore-api] [opFileProcessor] o.b.s.b.BookdropEventHandlerService      : File processing thread interrupted, shutting down.
2026-03-12T22:57:41.874-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.b.s.monitoring.LibraryWatchService     : Shutting down LibraryWatchService...
2026-03-12T22:57:41.874-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.b.s.watcher.LibraryFileEventProcessor  : Shutting down LibraryFileEventProcessor...
2026-03-12T22:57:41.875-04:00  WARN 16922 --- [booklore-api] [     watch-poll] o.b.s.monitoring.LibraryWatchService     : WatchService closed, stopping poll loop.
2026-03-12T22:57:41.882-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2026-03-12T22:57:41.886-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : BookloreHikariPool - Shutdown initiated...
2026-03-12T22:57:41.886-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : BookloreHikariPool - Shutdown completed.
2026-03-12T22:57:41.888-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.s.m.s.b.SimpleBrokerMessageHandler     : Stopping...
2026-03-12T22:57:41.888-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.s.m.s.b.SimpleBrokerMessageHandler     : BrokerAvailabilityEvent[available=false, SimpleBrokerMessageHandler [org.springframework.messaging.simp.broker.DefaultSubscriptionRegistry@532acfd7]]
2026-03-12T22:57:41.888-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.s.m.s.b.SimpleBrokerMessageHandler     : Stopped.
2026-03-12T22:57:41.890-04:00  INFO 16922 --- [booklore-api] [opFolderWatcher] o.b.s.b.BookdropMonitoringService        : Bookdrop monitor thread interrupted
2026-03-12T22:57:41.894-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.b.s.b.BookdropMonitoringService        : Stopped bookdrop folder monitor
2026-03-12T22:57:41.894-04:00  INFO 16922 --- [booklore-api] [opFileProcessor] o.b.s.b.BookdropEventHandlerService      : File processing thread interrupted, shutting down.
2026-03-12T22:57:41.896-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.b.s.monitoring.LibraryWatchService     : Shutting down LibraryWatchService...
2026-03-12T22:57:41.896-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] o.b.s.watcher.LibraryFileEventProcessor  : Shutting down LibraryFileEventProcessor...
2026-03-12T22:57:41.896-04:00  WARN 16922 --- [booklore-api] [     watch-poll] o.b.s.monitoring.LibraryWatchService     : WatchService closed, stopping poll loop.
2026-03-12T22:57:41.902-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2026-03-12T22:57:41.905-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : BookloreHikariPool - Shutdown initiated...
2026-03-12T22:57:41.906-04:00  INFO 16922 --- [booklore-api] [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : BookloreHikariPool - Shutdown completed.

[Incubating] Problems report is available at: file:///home/james/Projects/imnotjames/booklore/booklore-api/build/reports/problems/problems-report.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 10.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/9.4.0/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 2m 15s
6 actionable tasks: 3 executed, 3 up-to-date
Consider enabling configuration cache to speed up this build: https://docs.gradle.org/9.4.0/userguide/configuration_cache_enabling.html
```

</details>

<details>
<summary>Frontend test output (<code>ng test</code>)</summary>

```
Using Vitest configuration file: /home/james/Projects/imnotjames/booklore/booklore-ui/vitest-base.config.ts
Initial chunk files                                                            | Names                                                                       |  Raw size
spec-app-features-magic-shelf-component-magic-shelf-component.js               | spec-app-features-magic-shelf-component-magic-shelf-component               |   1.12 MB | 
spec-app-features-magic-shelf-service-book-rule-evaluator.service.js           | spec-app-features-magic-shelf-service-book-rule-evaluator.service           |  65.08 kB | 
spec-app-app.component.js                                                      | spec-app-app.component                                                      |  59.24 kB | 
chunk-OODOJWIH.js                                                              | -                                                                           |  55.00 kB | 
styles.css                                                                     | styles                                                                      |  31.02 kB | 
chunk-6GQKDBEE.js                                                              | -                                                                           |  25.09 kB | 
spec-app-features-magic-shelf-service-book-rule-evaluator-metadata-presence.js | spec-app-features-magic-shelf-service-book-rule-evaluator-metadata-presence |  23.21 kB | 
chunk-DTAZO7BH.js                                                              | -                                                                           |  15.75 kB | 
spec-app-features-magic-shelf-service-magic-shelf-utils.js                     | spec-app-features-magic-shelf-service-magic-shelf-utils                     |  11.36 kB | 
chunk-PUIDBMXW.js                                                              | -                                                                           |   6.10 kB | 
chunk-HMKTQGOO.js                                                              | -                                                                           |   4.92 kB | 
spec-app-core-security-auth-initializer.js                                     | spec-app-core-security-auth-initializer                                     |   4.73 kB | 
spec-app-features-book-service-library-health.service.js                       | spec-app-features-book-service-library-health.service                       |   2.95 kB | 
chunk-3J3QIHZF.js                                                              | -                                                                           |   2.19 kB | 
chunk-MUCKHQNJ.js                                                              | -                                                                           |   2.07 kB | 
chunk-HPNCK62B.js                                                              | -                                                                           |   1.33 kB | 
init-testbed.js                                                                | init-testbed                                                                |   1.27 kB | 
vitest-mock-patch.js                                                           | vitest-mock-patch                                                           | 481 bytes | 
spec-app-app.js                                                                | spec-app-app                                                                | 202 bytes | 
polyfills.js                                                                   | polyfills                                                                   | 121 bytes | 

                                                                               | Initial total                                                               |   1.43 MB

Application bundle generation complete. [4.348 seconds] - 2026-03-13T02:59:27.293Z

Watch mode enabled. Watching for file changes...

 DEV  v4.0.18 /home/james/Projects/imnotjames/booklore/booklore-ui

 ✓  booklore  src/app/features/magic-shelf/service/magic-shelf-utils.spec.ts (46 tests) 18ms
 ✓  booklore  src/app/app.spec.ts (1 test) 6ms
 ✓  booklore  src/app/features/book/service/library-health.service.spec.ts (6 tests) 46ms
 ✓  booklore  src/app/core/security/auth-initializer.spec.ts (2 tests) 30ms
 ✓  booklore  src/app/features/magic-shelf/service/book-rule-evaluator-metadata-presence.spec.ts (85 tests) 191ms
 ✓  booklore  src/app/features/magic-shelf/service/book-rule-evaluator.service.spec.ts (199 tests) 227ms
 ✓  booklore  src/app/app.component.spec.ts (7 tests) 229ms
 ✓  booklore  src/app/features/magic-shelf/component/magic-shelf-component.spec.ts (73 tests) 410ms

 Test Files  8 passed (8)
      Tests  419 passed (419)
   Start at  22:59:27
   Duration  2.79s (transform 1.55s, setup 2.53s, import 4.02s, tests 1.16s, environment 4.43s)

JUNIT report written to /home/james/Projects/imnotjames/booklore/booklore-ui/test-results/vitest-results.xml
 PASS  Waiting for file changes...
```

</details>

## 📸 Screen Recording / Screenshots (MANDATORY)

> Every PR must include a **screen recording or screenshots** showing the change working end-to-end in a running local instance (both backend and frontend). This means you must have actually built, run, and tested the code yourself. PRs without visual proof will be closed without review.

image

---

## ✅ Pre-Submission Checklist

> **All boxes must be checked before requesting review.** Incomplete PRs will be closed without review. No exceptions.

- [x] This PR is linked to an approved issue
- [x] Code follows project [backend and frontend conventions](../CONTRIBUTING.md#backend-conventions)
- [x] Branch is up to date with `develop` (merge conflicts resolved)
- [x] I ran the full stack locally (backend + frontend + database) and verified the change works
- [x] Automated tests added or updated to cover changes (backend **and** frontend)
- [x] All tests pass locally and output is pasted above
- [x] Screen recording or screenshots are attached above proving the change works
- [x] PR is a single focused change (one bug fix OR one feature, not multiple unrelated changes)
- [x] PR is reasonably scoped (PRs over 1000+ changed lines will be closed, split into smaller PRs)
- [x] No unsolicited refactors, cleanups, or "improvements" are bundled in
- [x] Flyway migration versioning is correct _(if schema was modified)_
- [x] Documentation PR submitted to [booklore-docs](https://github.com/booklore-app/booklore-docs) _(if user-facing changes)_

### 🤖 AI-Assisted Contributions

> **If any part of this PR was generated or assisted by AI tools (Copilot, Claude, ChatGPT, etc.), all items below are mandatory.** You are fully responsible for every line you submit. "The AI wrote it" is not an excuse, and AI-generated PRs that clearly haven't been reviewed are the #1 reason PRs get closed.

- [ ] I have read and understand every line of this PR and can explain any part of it during review
- [ ] I personally ran the code and verified it works (not just trusted the AI's output)
- [ ] PR is scoped to a single logical change, not a dump of everything the AI suggested
- [ ] Tests validate actual behavior, not just coverage (AI-generated tests often assert nothing meaningful)
- [ ] No dead code, placeholder comments, `TODO`s, or unused scaffolding left behind by AI
- [ ] I did not submit refactors, style changes, or "improvements" the AI suggested beyond the scope of the issue

---

### CODE REVIEW

**Comment by imnotjames** [comment]
I've ensured everything is filled out completely and the change is fully included.  This is not a draft pull request.

**Comment by acx10** [comment]
> I've ensured everything is filled out completely and the change is fully included. This is not a draft pull request.

So the one I merged was broken? Nice! 

PR 101: Always compile code and run tests locally before opening a PR.

This is why hesitant to merge PRs and people blame me for that.

**Comment by imnotjames** [comment]
> > I've ensured everything is filled out completely and the change is fully included. This is not a draft pull request.
> 
> So the one I merged was broken? Nice!

Yes.  It was a miscommunication on my part.

I had marked #3313 as a draft using the [Draft Pull Request feature](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests). I was still working through the checklist to confirm everything, so it was a work in progress.

I hadn't made it clear in the description or elsewhere of my intent of opening the work in progress to share with others.

> PR 101: Always compile code and run tests locally before opening a PR.

Thanks for the feedback.  I will avoid draft PRs for work in progress with this repo for the future.
